# Generated by Django 3.2.25 on 2026-04-11 10:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('approval_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalrequest',
            name='approver',
            field=models.ForeignKey(help_text='Level 1 Reviewer', on_delete=django.db.models.deletion.CASCADE, related_name='assigned_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='approvalrequest',
            name='status',
            field=models.CharField(choices=[('PENDING_REVIEW', 'Pending L1 Review'), ('PENDING_ADMIN', 'Pending L2 Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING_REVIEW', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin (Level 2)'), ('REQUESTER', 'Requester / Employee'), ('REVIEWER', 'Reviewer (Level 1)')], default='REQUESTER', max_length=20),
        ),
    ]
